---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: django-local-pv
  namespace: django                                   # todo
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/vol1/django-db
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-worker1
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
# about name:
#{{ .Release.Name }}=django+version or django;$version_label
  name: django-db
  namespace: django                                   # todo
  labels:
    app: django-db
spec:
  serviceName: django-db
  replicas: 1
  selector:
    matchLabels:
      app: django-db
  minReadySeconds: 20                                 # todo
  template:
    metadata:
      labels:
        app: django-db
    spec:
      terminationGracePeriodSeconds: 20               # todo
      containers:
        - name: django-db
          image: postgres:13-alpine
          volumeMounts:
            - name: django-local-pv
              mountPath: /var/lib/postgresql/data
          ports:
            - containerPort: 5432
              name: django-db-port
          env:
            - name: POSTGRES_DB
              value: "tutorial-dev"
            - name: POSTGRES_USER
              value: "vinhle"
            - name: POSTGRES_PASSWORD
              value: "password"
  volumeClaimTemplates:                               # auto create PVC
  - metadata:
      name: django-local-pv
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: local-storage
      resources:
        requests:
          storage: 5Gi
---
kind: Service
apiVersion: v1
metadata:
 name: django-db-in
 namespace: django                                     # todo
spec:
 type: NodePort
 selector:
   app: django-db
 ports:
 - protocol: TCP
   nodePort: 30001                                     # todo
   port: 5432                                          # todo
   targetPort: django-db-port
---
apiVersion: v1
kind: Pod
metadata:
  name: test-private-reg
  namespace: django
spec:
  containers:
  - name: test-private-reg-container
    image: k8s-automate:5000/test_nginx:0.1
  imagePullSecrets:
  - name: regcred

# ---
# kind: Service
# apiVersion: v1
# metadata:
#  name: django-db-in
#  namespace: django                                   # todo
# spec:
#   type: LoadBalancer
#   selector:
#     app: django-db
#   ports:
#   - protocol: TCP
#     nodePort: 30001
#     port: 5432
#     targetPort: django-db-port

#kind: Service
#apiVersion: v1
#metadata:
#  name: django-db-in
#  namespace: django                                   # todo
#spec:
#  type: NodePort
#  selector:
#    app: django-db
#  ports:
#  - protocol: TCP
#    nodePort: 30001
#    port: 5432
#    targetPort: django-db-port
# Service available from this and other nodes

#kind: Service
#apiVersion: v1
#metadata:
#  name: django-db-in
#  namespace: django                                   # todo
#spec:
#  selector:
#    app: web1-pod
#  ports:
#  - protocol: TCP
#    port: 5432
#    targetPort: django-db-port


#        command: ['sh', '-c', 'echo Hello Kubernetes from the Deployment! && sleep 3600']


