apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus-stack
    meta.helm.sh/release-namespace: monitoring
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/part-of: kube-state-metrics
    app.kubernetes.io/version: 2.9.2
    helm.sh/chart: kube-state-metrics-5.7.0
    release: prometheus-stack
  name: nodeport-prometheus-stack-kube-state-metrics
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 8880
    protocol: TCP
    targetPort: 8080
    nodePort: 30080
  selector:
    app.kubernetes.io/instance: prometheus-stack
    app.kubernetes.io/name: kube-state-metrics
  sessionAffinity: None
  type: NodePort

